spring:
  # 配置数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/form?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  # 配置模版引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  # 热部署
  devtools:
    restart:
      enabled: true

# 配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.habitdiary.form.entity

root-location: D:/formspace
